#!/bin/bash
COMMIT1=${2}
COMMIT2=${3}
OUTPUT_FILE=${1}
if [ $# -lt 2 ]; then
	echo "Usage: ${0} output_file commmit1 [commit2]"
	exit
fi
if [ $# -lt 2 ]; then
	COMMIT2='HEAD'
fi
git diff -z --name-only ${COMMIT1} ${COMMIT2} | xargs -0 git archive ${COMMIT2} -o ${OUTPUT_FILE} --
