#!/bin/bash
if [ $# -lt 3 ]; then
	echo "Usage: ${0} cmdGetList srcDir destDir"
	exit
fi
for file in $(${1}); do
	echo "......coping file ${2}/${file} to ${3}/${file}"
	cp ${2}/${file} ${3}/${file}
done
